//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    
    
    public partial class HotelRating
    {
        public int RatingID { get; set; }
        public int HotelID { get; set; }
        public int CustomerID { get; set; }
        public int Ratings { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public  Customer Customer { get; set; }
        public  Hotel Hotel { get; set; }
    }
}
