//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    
    
    public partial class MenuItem
    {
    
        public int MenuItemID { get; set; }
        public string Name { get; set; }
        public string MenuCategory { get; set; }
        public string AvailableFor { get; set; }
    
      
    }
}
